name: Build Application

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, macos-13]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: pyinstaller -w --onefile -i icon.png app.py

      - name: Copy additional files
        run: |
          cp reference.docx dist/
          cp example.env dist/
          cp reference.docx dist/
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Trans-PolyDocs-${{ matrix.os }}
          path: dist/
